# Lab - Regularization

## Week 4 Monday 11th January

In [15]:
## TASK: Regularized regression
## FUNCTIONS: Ridge, RidgeCV, Lasso, LassoCV
## DOCUMENTATION: http://scikit-learn.org/stable/modules/linear_model.html
## DATA: Crime (n=319 non-null, p=122, type=regression)
## DATA DICTIONARY: http://archive.ics.uci.edu/ml/datasets/Communities+and+Crime

## This data set contains data on violent crimes within a community.

########## Prepare data ##########
# read in data, remove categorical features, remove rows with missing values
import pandas as pd
crime = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data', header=None, na_values=['?'])

crime = crime.iloc[:, 5:]
crime.dropna(inplace=True)
crime.head()

# define X and y
X = crime.iloc[:, :-1]
y = crime.iloc[:, -1]

# split into train/test
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


In [14]:
x.head()

0    1      2                    3    4     5     6     7     8     9    \
0    8  NaN    NaN         Lakewoodcity    1  0.19  0.33  0.02  0.90  0.12   
1   53  NaN    NaN          Tukwilacity    1  0.00  0.16  0.12  0.74  0.45   
2   24  NaN    NaN         Aberdeentown    1  0.00  0.42  0.49  0.56  0.17   
3   34    5  81440  Willingborotownship    1  0.04  0.77  1.00  0.08  0.12   
4   42   95   6096    Bethlehemtownship    1  0.01  0.55  0.02  0.95  0.09   

   ...    118   119   120   121   122  123  124   125   126   127  
0  ...   0.12  0.26  0.20  0.06  0.04  0.9  0.5  0.32  0.14  0.20  
1  ...   0.02  0.12  0.45   NaN   NaN  NaN  NaN  0.00   NaN  0.67  
2  ...   0.01  0.21  0.02   NaN   NaN  NaN  NaN  0.00   NaN  0.43  
3  ...   0.02  0.39  0.28   NaN   NaN  NaN  NaN  0.00   NaN  0.12  
4  ...   0.04  0.09  0.02   NaN   NaN  NaN  NaN  0.00   NaN  0.03  

[5 rows x 128 columns]

In [17]:
# How many columns are in X? 122
print X.shape
print crime.shape

(319, 122)
(319, 123)


In [18]:
########## Linear Regression Model Without Regularization ##########
# linear regression
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train, y_train)
lm.coef_
# What are these numbers? These are all the beta coefficients .. Features 

array([ -3.66188167e+00,   6.98124465e-01,  -2.61955467e-01,
        -2.85270027e-01,  -1.64740837e-01,   2.46972333e-01,
        -1.09290051e+00,  -5.96857796e-01,   1.11200239e+00,
        -7.21968931e-01,   4.27346598e+00,  -2.28040268e-01,
         8.04875769e-01,  -2.57934732e-01,  -2.63458023e-01,
        -1.04616958e+00,   6.07784197e-01,   7.73552561e-01,
         5.96468029e-02,   6.90215922e-01,   2.16759430e-02,
        -4.87802949e-01,  -5.18858404e-01,   1.39478815e-01,
        -1.24417942e-01,   3.15003821e-01,  -1.52633736e-01,
        -9.65003927e-01,   1.17142163e+00,  -3.08546690e-02,
        -9.29085548e-01,   1.24654586e-01,   1.98104506e-01,
         7.30804821e-01,  -1.77337294e-01,   8.32927588e-02,
         3.46045601e-01,   5.01837338e-01,   1.57062958e+00,
        -4.13478807e-01,   1.39350802e+00,  -3.49428114e+00,
         7.09577818e-01,  -8.32141352e-01,  -1.39984927e+00,
         1.02482840e+00,   2.13855006e-01,  -6.18937325e-01,
         5.28954490e-01,

In [23]:
# make predictions and evaluate
import numpy as np
from sklearn import metrics
preds = lm.predict(X_test)
print 'RMSE (no regularization) =', np.sqrt(metrics.mean_squared_error(y_test, preds))

RMSE (no regularization) = 0.233813676495


In [24]:
########## Ridge Regression Model ##########
# ridge regression (alpha must be positive, larger means more regularization)
from sklearn.linear_model import Ridge
rreg = Ridge(alpha=0.1, normalize=True)
rreg.fit(X_train, y_train)
rreg.coef_
preds = rreg.predict(X_test)
print 'RMSE (Ridge reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))
# Is this model better? Why?

RMSE (Ridge reg.) = 0.164279068049


In [37]:
rregcv

RidgeCV(alphas=array([  1.00000e-02,   1.00000e-01,   1.00000e+00,   1.00000e+01,
         1.00000e+02]),
    cv=None, fit_intercept=True, gcv_mode=None, normalize=True,
    scoring='mean_squared_error', store_cv_values=True)

In [38]:
# use RidgeCV to select best alpha
from sklearn.linear_model import RidgeCV
alpha_range = 10.**np.arange(-2, 3)
rregcv = RidgeCV(normalize=True, scoring='mean_squared_error', alphas=alpha_range , store_cv_values=True)
rregcv.fit(X_train, y_train)#fit the ride
rregcv.alpha_
preds = rregcv.predict(X_test)
print 'RMSE (Ridge CV reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))
# What is the range of alp vlues we are searching over? We are searching from 1/100 to 1000

RMSE (Ridge CV reg.) = 0.163129782343


In [39]:
########## Lasso Regression Model ##########
# lasso (alpha must be positive, larger means more regularization)
from sklearn.linear_model import Lasso
las = Lasso(alpha=0.01, normalize=True)
las.fit(X_train, y_train)
las.coef_
preds = las.predict(X_test)
print 'RMSE (Lasso reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))

RMSE (Lasso reg.) = 0.198165225429


In [40]:
# try a smaller alpha
las = Lasso(alpha=0.0001, normalize=True)
las.fit(X_train, y_train)
las.coef_
preds = las.predict(X_test)
print 'RMSE (Lasso reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))


RMSE (Lasso reg.) = 0.164502413721


In [76]:
# use LassoCV to select best alpha (tries 100 alphas by default)
from sklearn.linear_model import LassoCV
alpha_range = 10.**np.arange(-3, 3)
lascv = LassoCV(normalize=True, alphas=alpha_range)
lascv.fit(X_train, y_train)
lascv.alpha_
lascv.coef_
preds = lascv.predict(X_test)
print 'RMSE (Lasso CV reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))

RMSE (Lasso CV reg.) = 0.160039024044


In [42]:
lascv.coef_

array([ 0.        ,  0.        ,  0.        , -0.03974695,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.        , -0.27503063,
       -0.        , -0.        , -0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.  

### Lookup [Elastic Net](http://scikit-learn.org/stable/modules/linear_model.html#elastic-net) and complete the following.



1. What is elastic net? It is a linear regression model incorporating the properties of Ridge Regression and and Lasso. This combination allows for learning a sparse model where few of the weights are non-zero like Lasso.
2. How does it work? It incorporates the L2 and L1 norms jointly into the model 
3. Run elastic net on the above dataset

In [74]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import lasso_path, enet_path , ElasticNetCV , ElasticNet




In [60]:
alpha_range = [0.0001, 0.001 , 0.01 , 0.1 ]

In [83]:
alpha_range = 10.**np.arange(-4, 4)

In [103]:
l1rat = [.1,0.25, 0.35, 0.45 ,.5, .7, .9, .95, .99, 1 ]

elascv = ElasticNetCV(l1rat, normalize=True , alphas=alpha_range)
elascv.fit(X_train, y_train)
elascv.alpha_
elascv.coef_
preds = elascv.predict(X_test)
print 'RMSE (ELasticNet CV reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))

RMSE (ELasticNet CV reg.) = 0.160104172083


In [101]:
alpha_range = np.linspace(0,1,1000)[1:-1]

In [102]:
#l1rat = [0.01, .1, 0.25, .5, .7, .9, .95, .99, 1 ,]

elascv = ElasticNetCV(lrat, normalize=True , alphas=alpha_range, max_iter=100000  )
elascv.fit(X_train, y_train)
elascv.alpha_
elascv.coef_
preds = elascv.predict(X_test)
print 'RMSE (ELasticNet CV reg.) =', np.sqrt(metrics.mean_squared_error(y_test, preds))

RMSE (ELasticNet CV reg.) = 0.160096084948


In [93]:
lrat = np.linspace(0,1,10)[1:-1]
lrat

array([ 0.11111111,  0.22222222,  0.33333333,  0.44444444,  0.55555556,
        0.66666667,  0.77777778,  0.88888889])